language: java

dist: trusty

jdk:
  - oraclejdk8
  
addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - pip install --user codecov

before_script:
  - psql -c "create user lrex with password 'loyalty';" -U postgres
  - createdb lrex-server -O lrex
  - ./gradlew :repository.pg:flywayMigrate

script:
  - ./gradlew codeCoverageReport

after_success:
  - codecov
  - ./gradlew buildBom
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*_bdio.jsonld

notifications:
  email:
    recipients:
      - talkto@nicholasvv.com
    on_success: change
    on_failure: always
